export  { default as get } from './get'
export  { default as checkTypes  } from './checkTypes'
export  { default as deepClone  } from './deepClone'
export  { default as isEmpty  } from './isEmpty'
export  { default as merge  } from './merge'